In [27]:
import pandas as pd

In [28]:
pref = pd.read_csv('../data/preferences/preference_labels_100.csv')
pref.head(5)

,id,topic,subtopic,prompt,difficulty,answer_a,answer_b,label,notes
0,dl_001,deep_learning,backpropagation,Explain backpropagation in simple language for...,easy,Simple Definition: Backpropagation is a method...,Backpropagation is an algorithm used in machin...,B,NaN
1,dl_002,deep_learning,backpropagation,What does the chain rule do during backpropaga...,easy,1. **Simple Definition**: The chain rule is a ...,The chain rule in backpropagation functions as...,B,NaN
2,dl_003,deep_learning,backpropagation,Why do neural networks use gradients during tr...,easy,1. **Simple Definition**: Neural networks use ...,Neural networks employ gradients during traini...,A,NaN
3,dl_004,deep_learning,backpropagation,Explain forward pass and backward pass in a ne...,easy,Simple Definition: The forward pass involves c...,The forward pass in a neural network refers to...,A,NaN
4,dl_005,deep_learning,backpropagation,Why can vanishing gradients make deep networks...,medium,Simple Definition: Vanishing gradients occur w...,Vanishing gradients in deep neural networks ca...,B,NaN

In [29]:
pref['label'].value_counts()

label
B       62
A       30
skip     3
Name: count, dtype: int64

In [32]:
pref['chosen'] = ""
pref['rejected'] = ""

In [ ]:
for i, row in pref.iterrows():
    if pref.loc[i, 'label'] == 'A':
        pref.loc[i, 'chosen'] == pref.loc[i, 'answer_a']
        pref.loc[i, 'rejected'] == pref.loc[i, 'answer_b']
    elif pref.loc[i, 'label'] == 'B':
        pref.loc[i, 'chosen'] == pref.loc[i, 'answer_b']
        pref.loc[i, 'rejected'] == pref.loc[i, 'answer_a']

In [34]:
pref

,id,topic,subtopic,prompt,difficulty,answer_a,answer_b,label,notes,chosen,rejected
0,dl_001,deep_learning,backpropagation,Explain backpropagation in simple language for...,easy,Simple Definition: Backpropagation is a method...,Backpropagation is an algorithm used in machin...,B,NaN,,
1,dl_002,deep_learning,backpropagation,What does the chain rule do during backpropaga...,easy,1. **Simple Definition**: The chain rule is a ...,The chain rule in backpropagation functions as...,B,NaN,,
2,dl_003,deep_learning,backpropagation,Why do neural networks use gradients during tr...,easy,1. **Simple Definition**: Neural networks use ...,Neural networks employ gradients during traini...,A,NaN,,
3,dl_004,deep_learning,backpropagation,Explain forward pass and backward pass in a ne...,easy,Simple Definition: The forward pass involves c...,The forward pass in a neural network refers to...,A,NaN,,
4,dl_005,deep_learning,backpropagation,Why can vanishing gradients make deep networks...,medium,Simple Definition: Vanishing gradients occur w...,Vanishing gradients in deep neural networks ca...,B,NaN,,
...,...,...,...,...,...,...,...,...,...,...,...
95,nlp_036,nlp,modern_models,Explain BART in simple language.,hard,Simple Definition: BART stands for Bayesian Ad...,BART stands for Bayesian Additive Regression T...,A,NaN,,
96,nlp_037,nlp,modern_models,What is the difference between encoder-only de...,hard,Simple definition: An encoder-only decoder-onl...,Encoder-Only Decoder-Only (EOD) Language Model...,B,NaN,,
97,nlp_038,nlp,rag,What is retrieval augmented generation in simp...,medium,Simple Definition: Retrieval Augmented Generat...,Retrieval Augmented Generation (RAG) is a tech...,B,NaN,,
98,nlp_039,nlp,rag,Why can RAG reduce hallucination in language m...,medium,Simple definition: RAG (Recurrent Attention Gr...,RAG (Recurrent Attention with Gated Recurrent ...,skip,RAG should be Retrieval Augmented Generation,,
99,nlp_040,nlp,evaluation,How do we evaluate whether an NLP model output...,medium,Simple Definition: Evaluating an NLP model's o...,To evaluate whether an NLP (Natural Language P...,B,NaN,,